import Head from 'next/head'

import { getAllFilesMetadata } from '../utils/mdxUtils'

import AppLayout from '../components/AppLayout'
import Container from '../components/Container'
import Section from '../components/Section'
import Footer from '../components/Footer'
import ArticlesList from '../components/ArticlesList'

export default function Home ({ posts }) {
  return (
    <>
      <Head>
        <title>vrom.dev 👨‍💻</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AppLayout>
        <Container>
          <Section
            title='Artículos publicados'
          >
            <ArticlesList
              posts={posts}
            />
          </Section>
          <Footer />
        </Container>
      </AppLayout>
    </>
  )
}

export async function getStaticProps () {
  const posts = await getAllFilesMetadata()
  return {
    props: { posts }
  }
}
