import Head from 'next/head'

import { getAllFilesMetadata } from '../utils/mdxUtils'

import AppLayout from '../components/AppLayout'
import Container from '../components/Container'
import Grid from '../components/Grid'
import Project from '../components/Project'
import Section from '../components/Section'
import CallToAction from '../components/CallToAction'
import Techs from '../components/Techs'
import Footer from '../components/Footer'
import ArticlesList from '../components/ArticlesList'

export default function Home ({ posts }) {
  return (
    <>
      <Head>
        <title>vrom.dev 👨‍💻</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AppLayout>
        <Container>
          <CallToAction />
          <Section
            title='Proyectos'
          >
            <Grid>
              <Project
                icon='👨‍🚀'
                title='Title.js'
                description='Interdum et malesuada fames ac ante ipsum primis in faucibus.'
                url='http://www.vrom.dev'
              />
              <Project
                icon='🔮'
                title='Title.js'
                description='Interdum et malesuada fames ac ante ipsum primis in faucibus.'
                url='http://www.vrom.dev'
              />
              <Project
                icon='⭐'
                title='Title.js'
                description='Interdum et malesuada fames ac ante ipsum primis in faucibus.'
                url='http://www.vrom.dev'
              />
            </Grid>
          </Section>
          <Section
            title='Artículos'
          >
            <ArticlesList
              posts={posts}
            />
          </Section>
          <Section
            title='Skills'
          >
            <Techs />
          </Section>
          <Footer />
        </Container>
      </AppLayout>
    </>
  )
}

export async function getStaticProps () {
  const posts = await getAllFilesMetadata()
  return {
    props: { posts }
  }
}
