import Head from 'next/head'

import styles from '../styles/Home.module.css'
import { Container } from '../components/Container'
import { Header } from '../components/Header'

export default function Home () {
  return (
    <>
      <Head>
        <title>vrom.dev 👨‍💻</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container>
        <Header />
        <h1 className={styles.title}>
          Hola! Soy <span className={styles.gradient}>Víctor Romero</span> 👋
        </h1>
        <p className={styles.bio}>
          Soy desarrollador fullstack, especializado en el ecosistema JavaScript. Un día descubrí el mundo de la programación, me enamoré de ello y me lancé a hacerlo mi profesión. Aprender es mi pasión.
        </p>
      </Container>
    </>
  )
}
