import Head from 'next/head'

// import styles from '../styles/Home.module.scss'
import { Container } from '../components/Container/Container'
import { Header } from '../components/Header/Header'
import { Grid } from '../components/Grid/Grid'
import { Project } from '../components/Project/Project'
import { Section } from '../components/Section/Section'
import { CallToAction } from '../components/CallToAction/CallToAction'
import { Techs } from '../components/Techs/Techs'
import { Footer } from '../components/Footer/Footer'

export default function Home () {
  return (
    <>
      <Head>
        <title>vrom.dev 👨‍💻</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Container>
        <CallToAction />
        <Section
          title='Proyectos'
        >
          <Grid>
            <Project
              icon='👨‍🚀'
              title='Title.js'
              description='Interdum et malesuada fames ac ante ipsum primis in faucibus.'
              url='http://www.vrom.dev'
            />
            <Project
              icon='🔮'
              title='Title.js'
              description='Interdum et malesuada fames ac ante ipsum primis in faucibus.'
              url='http://www.vrom.dev'
            />
            <Project
              icon='⭐'
              title='Title.js'
              description='Interdum et malesuada fames ac ante ipsum primis in faucibus.'
              url='http://www.vrom.dev'
            />
            <Project
              icon='💾'
              title='Title.js'
              description='Interdum et malesuada fames ac ante ipsum primis in faucibus.'
              url='http://www.vrom.dev'
            />
            <Project
              icon='🧛‍♂️'
              title='Title.js'
              description='Interdum et malesuada fames ac ante ipsum primis in faucibus.'
              url='http://www.vrom.dev'
            />
            <Project
              icon='👼'
              title='Title.js'
              description='Interdum et malesuada fames ac ante ipsum primis in faucibus.'
              url='http://www.vrom.dev'
            />
          </Grid>
        </Section>
        <Section
          title='Skills'
        >
          <Techs />
        </Section>
        <Footer />
      </Container>
    </>
  )
}
